[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Listing files:" && ls -la && echo "Models folder:" && ls -la models/']

[start]
cmd = 'node app.js'